pipeline:
  identifier: Build_sesha_04_guardian_1771490330075
  name: Build guardian
  orgIdentifier: default
  projectIdentifier: Demo
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github_OAuth_1771490027505
        repoName: sesha-04/guardian
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          caching:
            enabled: true
          cloneCodebase: true
          execution:
            steps:
              - step:
                  identifier: runtestsandcoverage
                  name: run tests and coverage
                  spec:
                    command: mvn clean verify
                    reports:
                      spec:
                        paths:
                          - "**/*.xml"
                      type: JUnit
                  timeout: ""
                  type: Run
              - step:
                  identifier: dockerbuild
                  name: docker_build
                  spec:
                    caching: true
                    connectorRef: <+input>
                    repo: hello/world
                    tags:
                      - latest
                  timeout: ""
                  type: BuildAndPushDockerRegistry
              - step:
                  type: ArtifactoryUpload
                  name: ArtifactoryUpload_1
                  identifier: ArtifactoryUpload_1
                  spec:
                    connectorRef: Jfrog
                    target: .
                    sourcePath: .
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
        type: CI
