name: CI

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  ci:
    name: CI
    runs-on:
      - ubuntu-24.04
    steps:
      - name: Checkout repo
        # v4.2.2
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Check formatting
        run: mvn -q com.spotify.fmt:fmt-maven-plugin:2.20:check

      - name: Test
        env:
          GUARDIAN_MYSQL_USER: user
          GUARDIAN_MYSQL_PASSWORD: password
          GUARDIAN_MYSQL_DATABASE: guardian
          GUARDIAN_REDIS_PORT: 6379
        run: mvn clean verify -Dlogback.configurationFile=logback/logback-development.xml

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@afb2984f4d89672b2f9d9c13ae23d53779671984
        if: always()
        with:
          files: |
            target/**/TEST-*.xml

      - name: Add coverage
        id: jacoco
        uses: madrapps/jacoco-report@50d3aff4548aa991e6753342d9ba291084e63848
        with:
          paths: |
            target/site/jacoco-it/jacoco.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          min-coverage-overall: 0
          update-comment: true
          title: Coverage Report
          pass-emoji: ':white_check_mark:'
          min-coverage-changed-files: 0
